#!/usr/bin/env sh

source "$(git --exec-path)/git-sh-setup"

USAGE="BRANCH"
function _recreate_branch() {
	if [[ -n $1 ]]; then
		git branch -D $1
		git push origin :$1
		git checkout -b $1
		git push origin -u $1
	else
		die "No branch specified"
	fi
}

_recreate_branch $1
