#!/usr/bin/env sh

source "$(git --exec-path)/git-sh-setup"

USAGE="MERGE"
function _merge_master() {
    git checkout master
    git pull --rebase
    git checkout -
    git merge master
}

_merge_master
