#!/bin/bash

function _setJavaVersion() {
  if [[ -z $1 ]]; then
    echo "No java version specified"
    exit 0
  fi
  export JAVA_HOME=$( /usr/libexec/java_home -v $1 )
  echo "Updated \$JAVA_HOME: $JAVA_HOME"
}

_setJavaVersion $1
