#!/usr/bin/env bash

java_version=$(java -version 2>&1 | awk -F '"' '/version/ {print $2}')
major=${java_version%%.*}
if [ $major -gt 1 ]; then
    version=$major
else
    minor_patch=${java_version#*.}
    version=${minor_patch%%.*}
fi
echo "$version"
